---
# tasks file for types
- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: show strings
  debug:
    msg: "{{ item }} is type {{ item | type_debug }}"
  loop: "{{ types_strings }}"

- name: test strings
  assert:
    that:
      - item is string
  loop: "{{ types_strings }}"

- name: show integers
  debug:
    msg: "{{ item }} is type {{ item | type_debug }}"
  loop: "{{ types_integers }}"

- name: test integers
  assert:
    that:
      - item is number
  loop: "{{ types_integers }}"

- name: show booleans
  debug:
    msg: "{{ item }} is type {{ item | type_debug }}"
  loop: "{{ types_booleans }}"

- name: test booleans
  assert:
    that:
      - item is boolean
  loop: "{{ types_booleans }}"

- name: show floats
  debug:
    msg: "{{ item }} is type {{ item | type_debug }}"
  loop: "{{ types_floats }}"

- name: test floats
  assert:
    that:
      - item is float
  loop: "{{ types_floats }}"
