---
# tasks file for types

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: show strings
  debug:
    msg: "{{ item }} is type {{ item | type_debug }}"
  loop: "{{ types_strings }}"

- name: test strings
  assert:
    that:
      - item is string
    quiet: yes
  loop: "{{ types_strings }}"

- name: show integers
  debug:
    msg: "{{ item }} is type {{ item | type_debug }}"
  loop: "{{ types_integers }}"

- name: test integers
  assert:
    that:
      - item is number
    quiet: yes
  loop: "{{ types_integers }}"

- name: show booleans
  debug:
    msg: "{{ item }} is type {{ item | type_debug }}"
  loop: "{{ types_booleans }}"

- name: test booleans
  assert:
    that:
      - item is boolean
    quiet: yes
  loop: "{{ types_booleans }}"

- name: show floats
  debug:
    msg: "{{ item }} is type {{ item | type_debug }}"
  loop: "{{ types_floats }}"

- name: test floats
  assert:
    that:
      - item is float
    quiet: yes
  loop: "{{ types_floats }}"

- name: show map
  debug:
    msg: "{{ types_map }} is type {{ types_map | type_debug }}"

- name: test map
  assert:
    that:
      - types_map is mapping
    quiet: yes
